config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  resources :sessions ,only: [:new, :create] do
    collection do
      delete 'logout' => :destroy
    end
  end
  get "/auth/:provider/callback" => 'sessions#create'
  get 'email/index'
  get 'email/today'
  get 'email/yesterday'
  get 'email/last_week'
  get '/email/:id', to: 'email#show' , :constraints => { :id => /.+@.+\..*/ }
  get '/email/show_email/:message_id', to: 'email#show_email', as: 'show_email'

end

app/models/email.rb
class Email < ActiveRecord::Base

end

app/models/token.rb
class Token < ActiveRecord::Base

# app/models/token.rb

  require 'net/http'
  require 'json'
    def to_params
      {'refresh_token' => refresh_token,
       'client_id' => ENV['CLIENT_ID'],
       'client_secret' => ENV['CLIENT_SECRET'],
       'grant_type' => 'refresh_token'}
    end

    def request_token_from_google
      url = URI("https://accounts.google.com/o/oauth2/token")
      Net::HTTP.post_form(url, self.to_params)
    end

    def refresh!
      response = request_token_from_google
      data = JSON.parse(response.body)
      update_attributes(
          access_token: data['access_token'],
          expires_at: Time.now + (data['expires_in'].to_i).seconds)
    end

    def expired?
      expires_at < Time.now
    end

    def fresh_token
      refresh! if expired?
      access_token
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :user_logged_in?, :current_user

  def authenticate!
    unless user_logged_in?
      flash[:notice]="Please login to continue."
      redirect_to root_path
    end
  end

  def user_logged_in?
    if session[:user]
      true
    else
      false
    end
  end

  def current_user
    session[:user]
  end
end

app/controllers/email_controller.rb
class EmailController < ApplicationController
  require 'json'
  require 'base64'
  layout false, only: :show_email
  before_filter :authenticate!
  def index
    email=Email.where(user: current_user).group(:email_from).count.select
    write_json(email)
  end

  def today
   email=Email.where(user: current_user).where('recieved_date > ?', Date.today).group(:email_from).count.select
    write_json(email)
   respond_to do |format|
     format.html
     format.js
   end
  end

  def yesterday
    email=Email.where(user: current_user).where('recieved_date < ? and recieved_date > ? ', Date.today,Date.yesterday).group(:email_from).count.select
    write_json(email)
  end

  def last_week
    email=Email.where(user: current_user).where('recieved_date > ? ', Date.today.beginning_of_week).group(:email_from).count.select
    write_json(email)
  end

  def show
      @messages= Email.where(user: current_user ,email_from: params[:id]).order(recieved_date: :desc)
  end

  def show_email
     @message= Email.where(user: current_user, message_id: params[:message_id]).first
  end

  private
  def write_json(email)
    File.open("public/temp.json","w") do |f|
      f.write('{"children": [')
      email.each do |k,v|
        f.write("{\"name\": #{k.to_json},")
        f.write('"children": [')
        f.write("{\"name\": #{k.to_json},")
        f.write("\"size\": #{v.to_json}}")
        f.write(']}')
        f.write(',') unless email.to_a.last.first.eql? k
      end
      f.write(']}')
      end
  end
=begin
  def authenticate!
    unless user_logged_in?
      flash[:notice]="Please login to continue."
      redirect_to root_path
    end
  end
=end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'login'
  def new
  end

  def create
    @auth = request.env['omniauth.auth']
    session[:user]=@auth[:info][:email]
    FetchEmails.perform_async(@auth['credentials']['token'],session[:user])
    redirect_to :email_index
  end

  def destroy
    if user_logged_in?
      reset_session
      redirect_to root_path, notice: 'Successfully Signed out!'
    end
  end
 end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/email_helper.rb
module EmailHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Gmail Bubble', root_path,class: "navbar-brand" %>
    </div>
    <% if user_logged_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "#{session[:user]}",'#' %></li>
          <li><%= link_to 'Logout', logout_sessions_path,method: 'delete' %></li>
        </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gmail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style>
      text {
          font: 10px sans-serif;
      }

  </style>

</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Gmail Bubble</a>
        </div>
      </div>
    </nav>

        <div class="container-fluid">
          <ul class="nav nav-tabs">
            <li class="<%= 'active' if current_page?(email_index_path) || current_page?(root_path) %>"><%= link_to "all", email_index_path%></li>
            <li class="<%= 'active' if current_page?(email_today_path) %>"><%= link_to "Today", email_today_path %></li>
            <li class="<%= 'active' if current_page?(email_yesterday_path) %>"><%= link_to "Yesterday", email_yesterday_path %></li>
          </ul>
            <%= yield %>
        </div><!-- /.container -->
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gmail Bubble</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application',"http://localhost:9292/faye.js", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style>
      text {
          font: 10px sans-serif;
      }

  </style>
</head>

<body>
<%= render 'layouts/header'%>

<div class="container-fluid">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <div class="jumbotron">
    <%= yield %>
  </div>
</div><!-- /.container -->
</body>
</html>